name: CI Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  

      - name: Create environment 
        run: make install
      
      - name: Format code
        run : make format

      - name: Lint the code
        run: make lint

      - name: Run tests
        run: make test_file